# Generated by Django 5.1.3 on 2026-10-07 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


DEFAULT_CATEGORIES = (
    ("Alimentation", "Courses, nourriture et boissons."),
    ("Transport", "Transports en commun, carburant et déplacements."),
    ("Logement", "Loyer, charges et entretien du logement."),
    ("Loisirs", "Activités de loisirs et sorties."),
    ("Santé", "Soins médicaux et dépenses de santé."),
    ("Vêtements", "Vêtements et accessoires."),
    ("Éducation", "Formation, livres et fournitures scolaires."),
    ("Divertissement", "Films, musique, jeux et abonnements."),
    ("Services", "Téléphone, internet et services du quotidien."),
    ("Épargne", "Épargne et placements de précaution."),
    ("Investissements", "Investissements et placements financiers."),
    ("Autres", "Dépenses ne correspondant à aucune autre catégorie."),
)


def seed_existing_users(apps, schema_editor):
    User = apps.get_model("api", "User")
    Category = apps.get_model("api", "Category")
    database = schema_editor.connection.alias

    for user in User.objects.using(database).iterator():
        Category.objects.using(database).bulk_create(
            [
                Category(user_id=user.pk, name=name, description=description)
                for name, description in DEFAULT_CATEGORIES
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_category_name_per_user')],
            },
        ),
        migrations.RunPython(seed_existing_users, migrations.RunPython.noop),
    ]
