# Generated by Django 5.1.3 on 2026-10-07 09:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('alert_threshold', models.DecimalField(blank=True, decimal_places=2, default=Decimal('80.00'), max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='api.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['user'], name='idx_budget_user_id'), models.Index(fields=['user', 'period_start', 'period_end'], name='idx_budget_user_period')],
                'constraints': [models.UniqueConstraint(fields=('user', 'category', 'period_start', 'period_end'), name='unique_budget_per_user_category_period'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='budget_amount_positive'), models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='budget_period_end_gte_start'), models.CheckConstraint(condition=models.Q(('alert_threshold__isnull', True), models.Q(('alert_threshold__gte', 0), ('alert_threshold__lte', 100)), _connector='OR'), name='budget_alert_threshold_valid_range')],
            },
        ),
    ]
